### ISSUE TITLE
Can not find `@EnableBatchAdmin`

### ISSUE THREAD

**Issue by m11y** [spring-projects/spring-batch-admin-samples#1]
Dependency `spring admin batch 2.0.0.BUILD-SNAPSHOT` could not find.

**Comment by mminella** [comment]
I'll update the build.gradle to add the snapshot repo.  The work around for now is to build the latest master branch of Spring Batch Admin locally.

**Comment by m11y** [comment]
I checked the spring snapshot repo `http://repo.spring.io/libs-snapshot/org/springframework/batch/spring-batch-admin-manager/2.0.0.BUILD-SNAPSHOT/`, and something weird.

The lastest build is `spring-batch-admin-manager-2.0.0.BUILD-20141110.104522-100.jar`.

**Comment by mminella** [comment]
This should now be fixed.  Sorry for the inconvenience and thanks for checking this out!  Feedback is appreciated!

**Comment by m11y** [comment]
@mminella Thank you, I already build the latest version locally. I am looking forward the release(or milestone ) of SBA.

**Comment by m11y** [comment]
I delete my locally build manually，and setup spring snapshot repo. It works! Thanks again.

**Comment by gpkreddy** [comment]
@mminella I am using @EnableBatchAdmin in spring boot but i am not seeing my jobs listed in the UI. 
is there anything else i need to do to make it work?
Does @EnableBatchAdmin work with spring boot?

**Comment by mminella** [comment]
@gpkreddy I'd have to see your code.  Are your jobs configured correctly (in the correct location)?

**Comment by gpkreddy** [comment]
I am not sure exactly what/how needs to be configured. I started with spring batch with boot. that worked fine. but then when i wanted to integrate batch-admin, i was completely lost. Finally, i made it to work,so now i am seeing batch-admin-ui with no jobs listed. 
Below is the configuration of a job that i was expecting to list in the UI. please let me know if I have to do any additional work or if i am missing anything. Thanks

@Configuration
@EnableBatchAdmin
@EnableAutoConfiguration(exclude=(HypermediaAutoConfiguration.class))
public class BatchConfiguration {

    // tag::readerwriterprocessor[]
    @Bean
    public ItemReader<EmailCompletion> reader() {
        FlatFileItemReader<EmailCompletion> reader = new FlatFileItemReader<EmailCompletion>();
        reader.setResource(new ClassPathResource("sample-data.csv"));
        reader.setLineMapper(new DefaultLineMapper<EmailCompletion>() {{
            setLineTokenizer(new DelimitedLineTokenizer() {{
                setNames(new String[] { "firstName", "lastName" });
            }});
            setFieldSetMapper(new BeanWrapperFieldSetMapper<EmailCompletion>() {{
                setTargetType(EmailCompletion.class);
            }});
        }});
        return reader;
    }

    @Bean
    public ItemProcessor<EmailCompletion, EmailCompletion> processor() {
       // return new EmailCompletionItemProcessor();
    	return null;
    }

    @Bean
    public ItemWriter<EmailCompletion> writer(DataSource dataSource) {
        JdbcBatchItemWriter<EmailCompletion> writer = new JdbcBatchItemWriter<EmailCompletion>();
        writer.setItemSqlParameterSourceProvider(new BeanPropertyItemSqlParameterSourceProvider<EmailCompletion>());
        writer.setSql("INSERT INTO people (first_name, last_name) VALUES (:firstName, :lastName)");
        writer.setDataSource(dataSource);
        return writer;
    }
    // end::readerwriterprocessor[]

    // tag::jobstep[]
    @Bean
    public Job importUserJob(JobBuilderFactory jobs, Step s1, JobExecutionListener listener) {
        return jobs.get("importUserJob")
                .incrementer(new RunIdIncrementer())
                .listener(listener)
                .flow(s1)
                .end()
                .build();
    }

    @Bean
    public Step step1(StepBuilderFactory stepBuilderFactory, ItemReader<EmailCompletion> reader,
            ItemWriter<EmailCompletion> writer, ItemProcessor<EmailCompletion, EmailCompletion> processor) {
        return stepBuilderFactory.get("step1")
                .<EmailCompletion, EmailCompletion> chunk(10)
                .reader(reader)
                .processor(processor)
                .writer(writer)
                .build();
    }
    // end::jobstep[]

    @Bean
    public JdbcTemplate jdbcTemplate(DataSource dataSource) {
        return new JdbcTemplate(dataSource);
    }

}

**Comment by gpkreddy** [comment]
@mminella I am finding difficulty in understanding what needs to be configured in Xml way and what can be done via java config and annotations. I am assuming @EnableBatchAdmin would do the remaining hooking up process. but looks like that is not case. Could you please elaborate on what @EnableBatchAdmin can automize the process?
Thanks

**Comment by gpkreddy** [comment]
@mminella ,
I am stuck here. could you please explain me what do you mean by correct location. I have your batch-admin-sample working, but when i refactor the package (org.springframework.batch.admin.sample) name to something else it doesn't work. why does the package/location matters?

Thanks

**Comment by mminella** [comment]
The package of your job or the whole thing?  That's the detail.  Component scanning (via Spring Boot) is going to scan org.springframework.batch.admin.sample unless you move the main class as well...

**Comment by gpkreddy** [comment]
Yes, All my jobs are under Main class and spring boot would be able to scan them. I did take care of that. but still its not reading them.

I did create a new project without using boot. I have some xml style jobs and java way configured jobs. All my xml jobs are showing up in Batch-admin UI but not java way configured jobs. Do i need to explicitly configure anything to tell the context to scan and read them as jobs? your batch-admin-sample works just fine until i change the package name under src/main/java  as shown below
![batch-admin](https://cloud.githubusercontent.com/assets/1399527/10611916/feed0a06-7713-11e5-8217-ec4897c3302c.PNG)

**Comment by mminella** [comment]
Where is the main class?  Is this code available on Github somewhere I can take a look?

**Comment by gpkreddy** [comment]
the above pic is not a spring boot one. It's the sample from your repo with just package name changed to com.tr (https://github.com/spring-projects/spring-batch-admin/tree/master/spring-batch-admin-sample).

For clarity sake, I am repeating this again. I created two projects to make this work. One with spring-boot and other a regular one (exactly similar to your batch-admin-sample). Both doesn't read my java jobs.

I will push my boot code to some repo and will share you the link. Meanwhile, you can check the screen shot of my spring-boot one

Thanks

![boot-batch-admin](https://cloud.githubusercontent.com/assets/1399527/10613491/00192bf6-771b-11e5-809d-e00a0ab4a00c.PNG)

**Comment by gpkreddy** [comment]
@mminella here is the link to boot repo
https://github.com/gpkreddy/batch_admin_test

**Comment by gpkreddy** [comment]
@mminella Any issues you identified in the code?. Thanks

**Comment by gpkreddy** [comment]
@mminella is that a bug?
 I am seeing below info in the stack trace. Why is it defaulting to the below location? Is that configurable at all?
 DEBUG localhost-startStop-1 support.PathMatchingResourcePatternResolver:424 - Resolved location pattern [classpath_:org/springframework/batch/admin/sample/job/__/_.class] to resources
